general:
steps:
  mtaBuild:
    buildTarget: 'CF'
  cloudFoundryDeploy:
    deployTool: 'mtaDeployPlugin'
    deployType: 'standard'
    cloudFoundry:
      org: 'China_Presales_demo2021'
      space: 'Dev'
      credentialsId: 'demo2021'
      apiEndpoint: 'https://api.cf.cn40.platform.sapcloud.cn'
    mtaDeployParameters: '-u deploy-service.cfapps.cn40.platform.sapcloud.cn'
  # cloudFoundryDeploy:
  #   deployTool: 'mtaDeployPlugin'
  #   deployType: 'standard'
  #   cloudFoundry:
  #     org: 'd0428b5ftrial'
  #     space: 'Dev'
  #     credentialsId: 'trial'
